#!/usr/bin/env bash

set -eu

NAME="init"
ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/${NAME}"

if [ ! -h gopath/src/${REPO_PATH} ]; then
        mkdir -p gopath/src/${ORG_PATH}
        ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

eval $(go env)

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

#echo "Building ${NAME}..."
#go build -o ${GOBIN}/${NAME} ${REPO_PATH}/tests
